before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: JXWgFst4Myy58mVqGUq7w6wOvDhW/PMCB+iu/ae8bXhiLDQuEBtpuNlMPvlW3P1+qry2RRxmdMaZte/uMTVCgfaYJxYQsMYC/KaLSwN5yJlUW2026gVCOh6TtfBIE+97LQ37+UdaE6+ntmmkSvC5nFB0Mw23A7fX6wuDSEOVMb3CDeDmLigLvHAy32dzk6fyynDL4yaq4IHh582VZ6l0Hoe4gCQ+goq0l1JwrS+MMJgkF5VOW8pgBLntY0RV+ggC9+EwTKDwtK26skVHGzRt52lzNkTqx2Z1+ROKyn4BJ7dff0S4y1eAEUeaXVHhvaS+AjOaZZ9qM0IvlCv/LGeOxhOMJnYHwksl5b/tszI7rf60nTkWWk1hmEyS7CK2SLJSd1u++dmQT8ChQObx9b8lplp9vg3dbpHQtBhGTnElrmj+M/5sGxiUbD+pvAd09noDThjy7dOBhAMYNrrnW4sJK0JvFsaQTnArurwmm3Rfk/BcLzwOBgOlUQrLn74cKCx4SWEziHOwid2jiqKnQrrMVfFUg3SumW0F56Adj+IyvSX33pqE4jfSCLRfuhcOj85FrRpdCrGsOwkvGwjqcKFoJW2X9APXFhjCHCKzq0oAfTASZnyKok6peJ3xfwF630VA7uxs6HX1IJK/++NWP0ulU2d+5t8EBQ/HqfVlMRmv8qo= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
